### PR TITLE
Docker support.

### PR DESCRIPTION
**Pull request by thewtex**
This pull request adds support for building, packaging, and testing the AppLauncher on Linux. This has multiple advantages.

- The package is built on an old version of CentOS, which has a glibc version that makes the binaries generated compatible with most Linux distributions.
- The CentOS Docker build image also has a newer version of the compiler, which generates better optimized binaries.
- The build steps are explicit and reproducible.
- The test suite can be automatically run on pull requests.
- A new package is automatically generate and is easily accessible after every merge.

This topic branch
- Adds a Dockerfile to build and package the repository.
- Adds a Dockerfile for an image with graphical support to run the test suite.
- Fixes the test suite to be compatible with the latest CMake (3.4.1).
- Adds CircleCI continuous integration configuration to test pull requests and generate a package artifact that can be downloaded.
- Adds a CircleCI status badge.

Before merging this pull request, testing for the repository should be enabled at circleci.com. Also in the CircleCI configuration for the project, DOCKER_EMAIL, DOCKER_USER, and DOCKER_PASS environmental variables should be defined for a user in the "commontk" DockerHub organization, which I created.  @jcfr was also added as an owner for that group.

After integration, the package can be downloaded via the "Artifacts" tab of a CircleCI build. The package will need to be renamed and repacked due to the way CircleCI automatically gzips its artifacts.

CC: @jcfr

### CODE REVIEW

**Comment by jcfr** [comment]
:+1:  Thanks for the outstanding work !

(( I will post comment on the different commit while reviewing in more details. ))

**Comment by jcfr** [comment]
Here is the error I saw on CircleCI:

```
docker run --name applauncher-test --volumes-from applauncher commontk/applauncher-test; docker cp applauncher-test:/var/log/supervisor/graphical-app-launcher.log - | tar xO; [ "$(docker cp applauncher-test:/tmp/graphical-app.return_code - | tar xO)" = 0 ]
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
2016-01-07 19:39:46,856 CRIT Supervisor running as root (no user in config file)
2016-01-07 19:39:46,856 WARN Included extra file "/etc/supervisor/conf.d/graphical-app-launcher.conf" during parsing
2016-01-07 19:39:46,857 WARN Included extra file "/etc/supervisor/conf.d/noVNC.conf" during parsing
2016-01-07 19:39:46,857 WARN Included extra file "/etc/supervisor/conf.d/x11vnc.conf" during parsing
2016-01-07 19:39:46,857 WARN Included extra file "/etc/supervisor/conf.d/xdummy.conf" during parsing
2016-01-07 19:39:46,872 INFO RPC interface 'supervisor' initialized
2016-01-07 19:39:46,872 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-07 19:39:46,873 INFO supervisord started with pid 1
2016-01-07 19:39:47,875 INFO spawned: 'graphical-app-launcher' with pid 9
2016-01-07 19:39:47,877 INFO spawned: 'noVNC' with pid 10
2016-01-07 19:39:47,879 INFO spawned: 'xdummy' with pid 11
2016-01-07 19:39:47,881 INFO spawned: 'x11vnc' with pid 12
2016-01-07 19:39:47,923 INFO success: graphical-app-launcher entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-01-07 19:39:48,965 INFO success: noVNC entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-07 19:39:48,965 INFO success: xdummy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-07 19:39:48,965 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-07 19:40:02,077 CRIT reaped unknown pid 867)
2016-01-07 19:40:26,917 INFO waiting for graphical-app-launcher, noVNC, xdummy, x11vnc to die
2016-01-07 19:40:26,921 INFO stopped: x11vnc (exit status 2)
2016-01-07 19:40:26,927 CRIT reaped unknown pid 307)
2016-01-07 19:40:26,927 CRIT reaped unknown pid 65)
2016-01-07 19:40:26,932 INFO exited: graphical-app-launcher (exit status 0; expected)
2016-01-07 19:40:27,922 INFO stopped: xdummy (exit status 1)
2016-01-07 19:40:27,922 CRIT reaped unknown pid 60)
2016-01-07 19:40:27,933 INFO stopped: noVNC (exit status 143)
2016-01-07 19:40:27,933 CRIT reaped unknown pid 37)
Error response from daemon: permission denied
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error response from daemon: permission denied
tar: This does not look like a tar archive

tar: Exiting with failure status due to previous errors docker run --name applauncher-test --volumes-from applauncher commontk/applauncher-test; docker cp applauncher-test:/var/log/supervisor/graphical-app-launcher.log - | tar xO; [ "$(docker cp applauncher-test:/tmp/graphical-app.return_code - | tar xO)" = 0 ] returned exit code 1
```

**Comment by thewtex** [comment]
Hmm.  The previous CircleCI build of this PR on my fork passed:

  https://circleci.com/gh/thewtex/AppLauncher/15

I will try pushing master there and see if it is reproducible.

**Comment by thewtex** [comment]
Addressed here:

  https://github.com/commontk/AppLauncher/pull/59

**Pull request merged**
