### PR TITLE
launcherlib: Add updateCurrentEnvironment() function

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @dzenanz

**Comment by jcfr** [comment]
Thanks for the review. Will merge as soon as TravisCI returns green

**Comment by dzenanz** [comment]
@jcfr All checks complete. Merge and integrate in Slicer?

**Comment by jcfr** [comment]
All set. See http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26436

**Pull request merged**
