### PR TITLE
ctkAppLauncher: Add support for interactive process

### PR DESCRIPTION
**Pull request by jcfr**
See http://blog.qt.io/blog/2006/03/16/starting-interactive-processes-with-qprocess/

Suggested-by: Isaiah Norton <inorton@bwh.harvard.edu>

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @lassoan

**Comment by jcfr** [comment]
* [ ] Add test checking that process is effectively interactive

**Comment by jcfr** [comment]
Cc: @ihnorton

**Comment by ihnorton** [comment]
```
macbook-pro:bin inorton$ ./SlicerPython
Python 2.7.13 (default, Apr  5 2018, 16:41:55)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

💯 👍

**Comment by lassoan** [comment]
@jcfr Where can I get the latest binary?

**Comment by jcfr** [comment]
For now, it turns out the easiest would be to build it locally against Qt4
or Qt5.

**Comment by lassoan** [comment]
Do you mean for testing only? (I don't have license for static Qt builds)

**Comment by jcfr** [comment]
For the sake of testing the interactive mode, you could just set the PATH
to include Qt before running the launcher.

**Comment by lassoan** [comment]
It did not work on Windows (no output appeared when started Python), but I could manage to fix it - see required change here: https://github.com/commontk/AppLauncher/pull/101#partial-pull-merging

(I've also added another fix for the error when launcher failed to start when .exe extension was not specified)

**Comment by jcfr** [comment]
Thanks :+1:  I posted few comments that should be addressed before we can integrated.

**Pull request merged**
